name: Deploy Main Branch

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Main
      uses: fjogeleit/http-request-action@master
      with:
        url: ${{ secrets.VERCEL_MAIN_DEPLOY }}
        method: 'POST'
